# Generated by Django 4.0 on 2023-03-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_analise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivos',
            name='nom_arquivo',
            field=models.CharField(max_length=200),
        ),
    ]
