# Generated by Django 4.0 on 2023-03-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_analise', '0002_alter_arquivos_nom_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivos',
            name='arquivo',
            field=models.FileField(upload_to='csv'),
        ),
        migrations.AlterField(
            model_name='arquivos',
            name='nom_arquivo',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
