# Generated by Django 4.0 on 2023-03-29 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_analise', '0003_alter_arquivos_arquivo_alter_arquivos_nom_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivos',
            name='arquivo',
            field=models.FileField(upload_to=''),
        ),
    ]
